version: '3.8'

services:
  db:
    image: postgres:14
    container_name: streaming_db
    environment:
      POSTGRES_USER: streamdata
      POSTGRES_PASSWORD: streamdata_password
      POSTGRES_DB: streaming_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streamdata -d streaming_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: streaming_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://streamdata:streamdata_password@db:5432/streaming_platform
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - KICK_CLIENT_ID=${KICK_CLIENT_ID}
      - KICK_CLIENT_SECRET=${KICK_CLIENT_SECRET}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - COLLECTION_INTERVAL_MINUTES=2
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
