# fly.toml app configuration file generated for streaming-dashboard-kiavash on 2025-10-07T10:29:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'streaming-dashboard-kiavash'
primary_region = 'iad'

[build]

[env]
  ENVIRONMENT = 'production'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
